name: CodexTestApp
options:
  bundleIdPrefix: com.codex
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    TARGETED_DEVICE_FAMILY: "1,2"
targets:
  CodexTestApp:
    type: application
    platform: iOS
    sources:
      - CodexTestApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.codex.codexTestApp
        INFOPLIST_FILE: CodexTestApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_VERSION: 5.0
    info:
      path: CodexTestApp/Info.plist
      properties:
        UILaunchScreen: {}
    scheme:
      testTargets: []
      gatherCoverageData: false
